import Link from "next/link";

type PageProps = { slug?: string[] };

const services = [
  ["Audit", "Independent reviews that give you a clear, confident picture of your business."],
  ["Financial Service Provider", "Practical financial guidance built around your goals and obligations."],
  ["Income Tax Planning", "Thoughtful tax planning that keeps more of your hard-earned value working."],
  ["SECP Compliance", "Company filings and compliance handled accurately and on time."],
  ["Company Profile Development", "A compelling company profile that makes your business memorable."],
  ["NTN Registration", "Get registered properly and start your tax journey with confidence."],
  ["Feasibility Report", "Turn an ambitious idea into an informed investment decision."],
  ["Freelancing", "Guidance for independent professionals, tax registration and compliance."],
  ["Bookkeeping", "Reliable, up-to-date records that keep your operations in control."],
  ["Sales Tax Consultancy", "Straightforward sales tax support for a changing regulatory landscape."],
  ["Digital Marketing", "Digital strategies that help the right customers find your business."],
  ["Account Maintaining", "Precise account maintenance for a healthier, more visible business."],
];

const blogs = [
  ["Tax Planning", "How practical tax planning can strengthen your business"],
  ["Business Growth", "Building a business that is prepared for its next opportunity"],
  ["Compliance", "A clearer approach to company compliance and reporting"],
  ["Financial Clarity", "The records every ambitious business needs to understand"],
  ["Freelancers", "A guide to registration and taxation for freelancers"],
  ["Consulting", "When to bring a financial consultant into your business"],
];

function titleCase(value: string) {
  return value.replace(/-/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

function Header() {
  return <>
    <div className="hidden bg-ink py-2 text-xs text-slate-200 md:block"><div className="shell flex justify-between"><span>Trusted corporate, financial &amp; legal guidance</span><a href="mailto:info@asconsultation.com">info@asconsultation.com</a></div></div>
    <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/95 backdrop-blur">
      <div className="shell flex h-[78px] items-center justify-between gap-6">
        <Link href="/" className="flex shrink-0 items-center"><img src="/images/logo%203ver.png" alt="AS Consultations" className="h-12 w-auto" /></Link>
        <nav className="hidden items-center gap-7 text-sm font-semibold text-ink lg:flex">
          <Link href="/">Home</Link><Link href="/about-us">About Us</Link><Link href="/service">Services</Link><Link href="/articles-list-style-2">Blogs</Link><Link href="/frequently-asked-questions">FAQs</Link>
        </nav>
        <Link href="/contact-us" className="button-primary hidden py-2.5 lg:inline-flex">Get in touch</Link>
        <details className="relative lg:hidden"><summary className="cursor-pointer list-none rounded border border-slate-200 px-3 py-2 text-sm font-bold text-ink">Menu</summary><nav className="absolute right-0 top-12 w-56 space-y-1 rounded bg-white p-3 shadow-soft"><Link className="block rounded px-3 py-2 hover:bg-mist" href="/">Home</Link><Link className="block rounded px-3 py-2 hover:bg-mist" href="/about-us">About us</Link><Link className="block rounded px-3 py-2 hover:bg-mist" href="/service">Services</Link><Link className="block rounded px-3 py-2 hover:bg-mist" href="/articles-list-style-2">Blogs</Link><Link className="block rounded px-3 py-2 hover:bg-mist" href="/contact-us">Contact us</Link></nav></details>
      </div>
    </header>
  </>;
}

function Footer() {
  return <footer className="bg-ink pt-16 text-slate-300"><div className="shell grid gap-12 pb-12 md:grid-cols-2 lg:grid-cols-4"><div><img src="/images/logo%203ver.png" alt="AS Consultations" className="mb-5 h-14 w-auto brightness-0 invert"/><p className="max-w-xs text-sm leading-7">Helping businesses make informed financial, tax and corporate decisions with confidence.</p></div><div><h3 className="mb-5 font-display text-xl text-white">Quick links</h3><div className="space-y-3 text-sm"><Link className="block hover:text-white" href="/about-us">About us</Link><Link className="block hover:text-white" href="/service">Our services</Link><Link className="block hover:text-white" href="/articles-list-style-2">Insights</Link><Link className="block hover:text-white" href="/contact-us">Contact us</Link></div></div><div><h3 className="mb-5 font-display text-xl text-white">Our services</h3><div className="space-y-3 text-sm"><Link className="block hover:text-white" href="/service/IncomeTaxPlanning">Income tax planning</Link><Link className="block hover:text-white" href="/service/SECPCompliance">SECP compliance</Link><Link className="block hover:text-white" href="/service/Bookkeeping">Bookkeeping</Link></div></div><div><h3 className="mb-5 font-display text-xl text-white">Contact</h3><address className="not-italic text-sm leading-7">Office #103, Sea Breeze Plaza<br/>Shahra-e-Faisal, Karachi<br/><a className="text-white hover:text-gold" href="mailto:info@asconsultation.com">info@asconsultation.com</a></address></div></div><div className="border-t border-white/10 py-5 text-center text-xs">© 2025 AS Consultation. Designed &amp; developed with care.</div></footer>;
}

function Hero() {
  return <section className="relative isolate overflow-hidden bg-ink"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,26,42,.93),rgba(5,26,42,.5)),url('/uploads/2024/10/home-01-slider-01.jpg')] bg-cover bg-center"/><div className="shell relative grid min-h-[650px] items-center py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="max-w-3xl text-white"><p className="mb-6 text-xs font-bold tracking-[.25em] text-gold">WELCOME TO AS CONSULTATIONS</p><h1 className="font-display text-5xl leading-[1.05] sm:text-6xl lg:text-7xl">Reliable corporate &amp; financial solutions, all in one place.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-200">Empower your business with practical advice, trusted representation, and finance solutions built around your success.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/contact-us" className="button-primary">Get a consultation <span className="ml-2">→</span></Link><Link href="/service" className="button-outline">Explore services</Link></div></div></div></section>;
}

function HomePage() {
  return <><Hero/><section className="bg-mist py-20"><div className="shell grid items-center gap-12 lg:grid-cols-[.8fr_1fr_1fr]"><img src="/uploads/2024/11/home-01-about.png" alt="AS Consultations team" className="mx-auto max-h-80 object-contain"/><div><p className="eyebrow">About AS Consultations</p><h2 className="font-display text-4xl leading-tight text-ink">Clear guidance for every important business decision.</h2></div><div><p className="leading-8">At AS Consultations, we combine financial insight, regulatory knowledge and a personal approach. Our team works closely with you to protect your interests and unlock your business potential.</p><Link href="/about-us" className="mt-6 inline-block font-bold text-brand">Discover our story →</Link></div></div></section><section className="shell py-24"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">What we do</p><h2 className="font-display text-4xl text-ink">Services designed around your goals.</h2></div><Link href="/service" className="font-bold text-brand">View all services →</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.slice(0, 6).map(([title, description], index) => <Link href={`/service/${title.replaceAll(" ", "")}`} key={title} className="group border border-slate-100 p-7 shadow-sm transition hover:-translate-y-1 hover:border-brand hover:shadow-soft"><span className="mb-8 block font-display text-3xl text-gold">0{index + 1}</span><h3 className="font-display text-2xl text-ink group-hover:text-brand">{title}</h3><p className="mt-3 text-sm leading-7">{description}</p><span className="mt-6 inline-block font-bold text-brand">Learn more →</span></Link>)}</div></section><section className="bg-ink py-20 text-white"><div className="shell grid gap-12 lg:grid-cols-[1fr_1.2fr]"><div><p className="eyebrow text-gold">Why choose us</p><h2 className="font-display text-4xl leading-tight">Experience that brings clarity and momentum.</h2><p className="mt-6 max-w-md leading-8 text-slate-300">We bring the discipline of a trusted adviser and the responsiveness of a committed partner to every conversation.</p></div><div className="grid gap-x-8 gap-y-10 sm:grid-cols-2">{[["Expert team", "Specialist support where it matters most."],["Best service", "A thoughtful experience from first call to final result."],["Free consultation", "Start with a clear, no-pressure conversation."],["Customer support", "Responsive help when you need an answer."]].map(([title, text], i) => <div key={title} className="border-l border-gold pl-5"><span className="text-gold">0{i + 1}</span><h3 className="mt-2 font-display text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section><Insights/><Cta/></>;
}

function Insights() { return <section className="shell py-24"><div className="mb-12 text-center"><p className="eyebrow">Latest insights</p><h2 className="font-display text-4xl text-ink">Knowledge for smarter decisions.</h2></div><div className="grid gap-6 md:grid-cols-3">{blogs.slice(0,3).map(([tag, title], index) => <article key={title} className="overflow-hidden border border-slate-100 bg-white shadow-sm"><img src={`/uploads/2024/11/blog-img-0${index + 1}.jpg`} alt="" className="h-52 w-full object-cover"/><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-brand">{tag}</p><h3 className="mt-3 font-display text-2xl leading-snug text-ink">{title}</h3><Link href={`/custom-blogs/blog-${index + 1}`} className="mt-5 inline-block text-sm font-bold text-brand">Read article →</Link></div></article>)}</div></section>; }

function Cta() { return <section className="bg-mist py-20"><div className="shell grid items-center gap-8 md:grid-cols-2"><div><p className="eyebrow">Let&apos;s talk</p><h2 className="font-display text-4xl text-ink">Your solution is just a click away.</h2></div><div className="md:justify-self-end"><p className="mb-5 max-w-md leading-7">Tell us what you are working through. Our team is ready to offer a useful next step.</p><Link className="button-primary" href="/contact-us">Contact our team →</Link></div></div></section>; }

function PageHero({ title, trail = "Home" }: { title: string; trail?: string }) {
  return <section className="relative overflow-hidden bg-ink py-24 text-white"><div className="absolute inset-0 bg-[linear-gradient(rgba(5,26,42,.86),rgba(5,26,42,.9)),url('/uploads/2024/10/breadcrumb-image.jpg')] bg-cover bg-center"/><div className="shell relative"><p className="text-sm text-slate-300">{trail} <span className="mx-2 text-gold">/</span> {title}</p><h1 className="mt-3 font-display text-5xl">{title}</h1></div></section>;
}

function AboutPage() { return <><PageHero title="About Us"/><section className="shell grid gap-12 py-24 lg:grid-cols-2"><div><p className="eyebrow">Who we are</p><h2 className="font-display text-4xl leading-tight text-ink">A dependable partner for your business journey.</h2><p className="mt-6 leading-8">AS Consultations provides sound corporate, tax and financial support to businesses and professionals. We pair deep technical knowledge with advice that is direct, useful and personal.</p><p className="mt-4 leading-8">Every engagement starts by understanding the people and ambitions behind the numbers. Then we build a clear route forward.</p><Link className="button-primary mt-8" href="/contact-us">Work with us →</Link></div><div className="grid grid-cols-2 gap-4"><img className="mt-12 h-72 w-full object-cover" src="/uploads/2024/11/team-01.jpg" alt="Consultation meeting"/><img className="h-72 w-full object-cover" src="/uploads/2024/11/team-02.jpg" alt="AS Consultations team"/></div></section><section className="bg-mist py-20"><div className="shell grid gap-6 md:grid-cols-3">{[["Integrity", "Advice shaped by the long-term interests of our clients."],["Precision", "Careful work and clear communication at every stage."],["Partnership", "A responsive team that is invested in your success."]].map(([title,text])=><div className="bg-white p-8 shadow-sm" key={title}><span className="text-gold">✦</span><h3 className="mt-4 font-display text-2xl text-ink">{title}</h3><p className="mt-3 leading-7">{text}</p></div>)}</div></section><Cta/></>; }

function ServicesPage() { return <><PageHero title="Our Services"/><section className="shell py-24"><div className="mx-auto mb-14 max-w-2xl text-center"><p className="eyebrow">How we help</p><h2 className="font-display text-4xl text-ink">The support your business needs, in one place.</h2><p className="mt-5 leading-7">Choose focused support for one need or a wider partnership across your business.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([title, description], index)=><Link href={`/service/${title.replaceAll(" ", "")}`} key={title} className="group border border-slate-100 p-7 transition hover:border-brand hover:shadow-soft"><span className="font-display text-3xl text-gold">{String(index+1).padStart(2,"0")}</span><h2 className="mt-7 font-display text-2xl text-ink group-hover:text-brand">{title}</h2><p className="mt-3 text-sm leading-7">{description}</p><span className="mt-6 inline-block text-sm font-bold text-brand">Explore service →</span></Link>)}</div></section><Cta/></>; }

function ServiceDetail({ title }: { title: string }) { const service = services.find(([name]) => name.toLowerCase().replaceAll(" ", "") === title.toLowerCase().replaceAll("-", "")); const name = service?.[0] ?? titleCase(title); return <><PageHero title={name} trail="Services"/><section className="shell grid gap-12 py-24 lg:grid-cols-[1.2fr_.8fr]"><article><p className="eyebrow">AS Consultations service</p><h2 className="font-display text-4xl leading-tight text-ink">Professional {name.toLowerCase()} support, tailored to you.</h2><p className="mt-6 leading-8">{service?.[1] ?? "Our team provides practical, timely support shaped around your business goals and regulatory requirements."}</p><p className="mt-4 leading-8">We simplify the technical details, identify the priorities and keep you informed throughout. You get a considered solution and the confidence to move forward.</p><h3 className="mt-10 font-display text-2xl text-ink">What you can expect</h3><ul className="mt-5 grid gap-3 text-sm leading-6 sm:grid-cols-2"><li>✓ Clear, useful guidance</li><li>✓ A tailored action plan</li><li>✓ Timely, accurate delivery</li><li>✓ Ongoing support</li></ul></article><aside className="bg-mist p-8"><h3 className="font-display text-3xl text-ink">Need advice?</h3><p className="mt-4 leading-7">Speak with our team about your next step.</p><Link href="/contact-us" className="button-primary mt-7">Request consultation →</Link><div className="mt-10 border-t border-brand/20 pt-6 text-sm"><p className="font-bold text-ink">Email us</p><a className="mt-1 block text-brand" href="mailto:info@asconsultation.com">info@asconsultation.com</a></div></aside></section></>; }

function BlogPage({ article }: { article?: string }) { const selected = article ? blogs.find((_, index) => `blog-${index+1}` === article) : undefined; if (article) { const [tag,title] = selected ?? ["Insights", titleCase(article)]; return <><PageHero title={title} trail="Insights"/><article className="shell max-w-4xl py-24"><p className="eyebrow">{tag}</p><h2 className="font-display text-4xl leading-tight text-ink">{title}</h2><img className="my-9 h-[380px] w-full object-cover" src="/uploads/2024/10/blog-image-1.jpg" alt="Business insight"/><div className="space-y-5 leading-8"><p>In a complex business environment, the best decisions are rooted in a clear understanding of the numbers, obligations and opportunities in front of you.</p><p>Our advisers work alongside clients to make financial and regulatory matters less daunting. With the right preparation and trusted support, you can focus on building the business you want.</p><h3 className="font-display text-2xl text-ink">A practical next step</h3><p>Every situation is different. A short conversation can help identify what deserves attention now and what can wait.</p></div></article><Cta/></>; } return <><PageHero title="Insights & Articles"/><section className="shell py-24"><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{blogs.map(([tag,title],index)=><article key={title} className="border border-slate-100 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.15em] text-brand">{tag}</p><h2 className="mt-4 font-display text-2xl leading-snug text-ink">{title}</h2><p className="mt-4 text-sm leading-7">Practical insight from the AS Consultations team.</p><Link className="mt-6 inline-block font-bold text-brand" href={`/custom-blogs/blog-${index+1}`}>Read more →</Link></article>)}</div></section></>; }

function ContactPage() { return <><PageHero title="Contact Us"/><section className="shell grid gap-12 py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Start a conversation</p><h2 className="font-display text-4xl text-ink">We&apos;re here to help.</h2><p className="mt-6 leading-8">Send us a message to discuss your needs. We&apos;ll get back to you with a helpful next step.</p><div className="mt-9 space-y-6"><div><p className="font-bold text-ink">Email</p><a href="mailto:info@asconsultation.com" className="text-brand">info@asconsultation.com</a></div><div><p className="font-bold text-ink">Office</p><p className="mt-1 leading-7">Office #103, First Floor, Sea Breeze Plaza,<br/>Shahra-e-Faisal, Karachi, Sindh 75300</p></div></div></div><form className="grid gap-5 bg-mist p-7 sm:grid-cols-2 sm:p-10"><label className="text-sm font-bold text-ink">First name<input required className="mt-2 w-full border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-brand" /></label><label className="text-sm font-bold text-ink">Last name<input className="mt-2 w-full border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-brand" /></label><label className="text-sm font-bold text-ink sm:col-span-2">Email<input type="email" required className="mt-2 w-full border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-brand" /></label><label className="text-sm font-bold text-ink sm:col-span-2">Phone<input type="tel" className="mt-2 w-full border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-brand" /></label><label className="text-sm font-bold text-ink sm:col-span-2">Message<textarea required rows={5} className="mt-2 w-full border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-brand" /></label><button className="button-primary w-fit sm:col-span-2" type="submit">Send message →</button></form></section></>; }

function FaqPage() { const questions = ["What services does AS Consultations offer?", "How can I book a consultation?", "Do you support businesses of every size?", "Can you help with SECP and tax compliance?"]; return <><PageHero title="Frequently Asked Questions"/><section className="shell max-w-4xl py-24"><p className="eyebrow text-center">Helpful answers</p><h2 className="mb-10 text-center font-display text-4xl text-ink">Questions, answered clearly.</h2>{questions.map((question,index)=><details key={question} className="mb-4 border border-slate-200 p-5 open:border-brand"><summary className="cursor-pointer font-display text-xl text-ink">{question}</summary><p className="mt-4 max-w-2xl leading-7">Our team offers practical guidance tailored to your circumstances. Contact us for a short conversation and we will point you toward the right service and next step.</p></details>)}</section></>; }

function CollectionPage({ title, kind }: { title: string; kind: "portfolio" | "team" | "shop" | "listing" | "account" }) { const data = kind === "team" ? [["Ayesha Shah", "Managing Partner", "/uploads/2024/11/team-01.jpg"],["Usman Raza", "Financial Consultant", "/uploads/2024/11/team-02.jpg"],["Sara Ahmed", "Tax Consultant", "/uploads/2024/11/team-03.jpg"]] : kind === "portfolio" || kind === "listing" ? [["Business advisory", "Corporate solutions", "/uploads/2024/11/portfolio-01.jpg"],["Financial planning", "Informed growth", "/uploads/2024/11/portfolio-02.jpg"],["Compliance support", "Trusted representation", "/uploads/2024/11/portfolio-03.jpg"]] : kind === "shop" ? [["Business consultation", "Professional support", "/uploads/2024/11/product-01.jpg"],["Corporate documentation", "Business service", "/uploads/2024/11/product-02.jpg"],["Financial review", "Consulting service", "/uploads/2024/11/product-03.jpg"]] : []; if (kind === "account") return <><PageHero title={title}/><section className="shell max-w-lg py-24"><div className="border border-slate-200 p-8 shadow-sm"><h2 className="font-display text-3xl text-ink">Welcome back</h2><p className="mt-3 text-sm leading-6">Use your account to manage your consultations and services.</p><form className="mt-7 grid gap-4"><input aria-label="Email address" placeholder="Email address" className="border border-slate-200 px-4 py-3 outline-none focus:border-brand"/><input aria-label="Password" type="password" placeholder="Password" className="border border-slate-200 px-4 py-3 outline-none focus:border-brand"/><button className="button-primary w-full">Continue</button></form></div></section></>; return <><PageHero title={title}/><section className="shell py-24"><div className="mb-12 max-w-2xl"><p className="eyebrow">AS Consultations</p><h2 className="font-display text-4xl text-ink">Explore our {kind === "team" ? "people" : "work"}.</h2></div><div className="grid gap-6 md:grid-cols-3">{data.map(([name, subtitle, image])=><article key={name} className="overflow-hidden bg-white shadow-soft"><img src={image} className="h-64 w-full object-cover" alt={name}/><div className="p-6"><h3 className="font-display text-2xl text-ink">{name}</h3><p className="mt-2 text-sm text-brand">{subtitle}</p>{kind === "shop" && <button className="mt-5 text-sm font-bold text-brand">Add to enquiry →</button>}</div></article>)}</div></section></>; }

export function SitePage({ slug = [] }: PageProps) { const path = slug.join("/"); let content: React.ReactNode; if (!path) content = <HomePage/>; else if (path === "about-us") content = <AboutPage/>; else if (path === "service") content = <ServicesPage/>; else if (path.startsWith("service/")) content = <ServiceDetail title={slug.at(-1) ?? "Service"}/>; else if (path === "contact-us") content = <ContactPage/>; else if (path === "frequently-asked-questions") content = <FaqPage/>; else if (path === "articles-list-style-2") content = <BlogPage/>; else if (path.startsWith("custom-blogs/") || path.startsWith("blog/")) content = <BlogPage article={slug.at(-1)}/>; else if (path === "our-portfolio" || path.startsWith("listings/")) content = <CollectionPage title={path.startsWith("listings/") ? titleCase(slug.at(-1) ?? "Case study") : "Our Portfolio"} kind={path.startsWith("listings/") ? "listing" : "portfolio"}/>; else if (path === "our-lawyers") content = <CollectionPage title="Our Team" kind="team"/>; else if (path === "shop" || path.startsWith("product/")) content = <CollectionPage title={path.startsWith("product/") ? titleCase(slug.at(-1) ?? "Service") : "Our Services"} kind="shop"/>; else if (["cart", "checkout", "wishlist", "register"].includes(path) || path.startsWith("my-account/")) content = <CollectionPage title={titleCase(slug.at(-1) ?? path)} kind="account"/>; else if (path === "pricing-plans") content = <CollectionPage title="Pricing Plans" kind="shop"/>; else if (["landing-page", "home-1"].includes(path)) content = <HomePage/>; else content = <BlogPage article={slug.at(-1)}/>; return <><Header/><main>{content}</main><Footer/></>; }
